language: python
matrix:
  include:
    - python: 3.6
      env: DJANGO=1.11 TOXENV=py36-django111
    - python: 3.6
      env: DJANGO=2.22 TOXENV=py36-django222

install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
