language: python
matrix:
  include:
    - python: 2.7
      env: DJANGO=1.11 TOXENV=docs
    - python: 2.7
      env: DJANGO=1.11 TOXENV=pep8
    - python: 2.7
      env: DJANGO=1.11 TOXENV=py27-django111
    - python: 3.6
      env: DJANGO=1.11 TOXENV=py36-django111
    - python: 3.6
      env: DJANGO=2.0 TOXENV=py36-django20
    - python: 3.6
      env: DJANGO=2.1 TOXENV=py36-django21
    - python: 3.6
      env: DJANGO=2.2 TOXENV=py36-django22


install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
